// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetIsExecuting():Promise<boolean>;

export function LoadLastFile():Promise<main.FlowData>;

export function SaveFile(arg1:main.FlowData):Promise<string>;

export function StartExecution(arg1:string):Promise<void>;

export function StopExecution():Promise<void>;
