// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIsExecuting() {
  return window['go']['main']['App']['GetIsExecuting']();
}

export function LoadLastFile() {
  return window['go']['main']['App']['LoadLastFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function StartExecution(arg1) {
  return window['go']['main']['App']['StartExecution'](arg1);
}

export function StopExecution() {
  return window['go']['main']['App']['StopExecution']();
}
