// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSession():Promise<main.SessionResponse>;

export function Login(arg1:main.LoginRequest):Promise<main.LoginResponse>;

export function Logout():Promise<main.LogoutResponse>;

export function ValidateStoredToken(arg1:string):Promise<main.SessionResponse>;
